[package]
name = "tree-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
jmt = "0.12.0"
blake2 = "0.10"

[dev-dependencies]
criterion = "0.5"
tempfile = "3.8"
sha2 = "0.10"
bcs = "0.1"
bincode = "1.3"
anyhow = "1.0"
